### ISSUE TITLE
This plugin generated a warning from the characteristic 'On'

### ISSUE THREAD

**Issue by cirrusflyer** [athal7/homebridge-hyundai-bluelink#6]
**Describe The Bug:**
See errors in Homebridge logs, and doesn't seem to work in Home app.

**To Reproduce:**
installed and configured plugin

**Expected behavior:**
No errors and working plugin

**Logs:**
[2/22/2021, 11:01:20 PM] [Hyundai] Starting Vehicle
[2/22/2021, 11:01:22 PM] [Hyundai] Start Response Failed to start vehicle
[2/22/2021, 11:01:22 PM] [homebridge-hyundai-bluelink] This plugin generated a warning from the characteristic 'On': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

**Plugin Config:**

{
            "credentials": {
                "username": "email@email.com",
                "password": "zxvcfdddfdfdfdfdf",
                "region": "US",
                "pin": "0000"
            },
            "vehicles": [
                {
                    "vin": "ABCDEFGHIJKLMNOP",
                    "maxRange": 42
                }
            ],
            "remoteStart": {
                "cool": true,
                "heat": true,
                "defrost": true,
                "igniOnDuration": 15
            },
            "refreshInterval": 600,
            "platform": "Hyundai"
        }

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.11
* **Homebridge Version**: 1.3.0
* Nodejs Version:  v14.15.5
* Npm Version: v6.14.11
* **Operating System**: Docker

**Comment by athal7** [comment]
Thanks for the report! For the specific error about undefined, that happens when homebridge asks for the status before we have heard back from Hyundai for the first time on whether the car is on or off. I guess if we have to return one of the two values it should return that the car is off?

The other error in the log was related to actually starting the car erroring. @scottdlowe was doing some digging in #4 on that one, was waiting to hear back re API limits.
